# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
    viewport:      width=device-width, initial-scale=1.0

  stylesheets:
    - bootstrap
    - datepicker
    - chosen-full
    - tablesorter
    - backend

  javascripts:
    - "http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"
    - bootstrap.min.js
    - bootstrap-datepicker.js
    - bootstrap-datepicker.ru.js
    - choosen.jquery.js
    - tiny_mce/tiny_mce.js
    - jquery.tablesorter.js
    - mceinit.js

  has_layout:     true
  layout:         layout
