<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cheapon
 * @subpackage model
 * @author     slowpokes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
  public function getEventsCount()
  {
    $q = Doctrine_Query::create()
      ->select('COUNT(e.id) as number_of_events')
      ->from('Category c')
      ->leftJoin('c.Event e')
      ->where('c.id = ?', $this->id);
   
    return $q->fetchOne()->getNumberOfEvents();
  }
  
  public function save(Doctrine_Connection $conn = null)
  {
    if ($this->isNew())
    {
      $this->setSort(Doctrine_Core::getTable('Category')->getMaxSort() + 1);
    }
 
    return parent::save($conn);
  }
  
  public function delete(Doctrine_Connection $conn = null)
  {
    $questions = Doctrine_Query::create()
      ->from('Category c')
      ->where('c.sort > ?', $this->getSort())
      ->execute();
 
    foreach($questions as $question)
    {
      $question->setSort($question->getSort() - 1);
      $question->save();
    }
 
    return parent::delete($conn);
  }
}
