<?php

/**
 * City
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cheapon
 * @subpackage model
 * @author     slowpokes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class City extends BaseCity
{
  public function getProviderCount()
  {
    $q = Doctrine_Query::create()
      ->select('COUNT(p.id) as number_of_providers')
      ->from('City c')
      ->leftJoin('c.Provider p')
      ->where('c.id = ?', $this->id);
   
    return $q->fetchOne()->getNumberOfProviders();
  }
  public function getClientCount()
  {
    $q = Doctrine_Query::create()
      ->select('COUNT(p.id) as number_of_clients')
      ->from('City c')
      ->leftJoin('c.Client p')
      ->where('c.id = ?', $this->id);
   
    return $q->fetchOne()->getNumberOfClients();
  }
}
