<?php

/**
 * CityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('City');
    }

    public static function getDefaultCity()
    {
      return Doctrine_Query::create()
        ->from('City c')
        ->addWhere('c.is_default = ?', true)
        ->limit(1)
        ->fetchOne()
      ;
    }

    public static function findOneBySlug($slug)
    {
      return Doctrine_Query::create()
        ->from('City c')
        ->addWhere('c.slug = ?', $slug)
        ->limit(1)
        ->fetchOne()
      ;
    }

    public static function findOneByName($name)
    {
      return Doctrine_Query::create()
        ->from('City c')
        ->addWhere('c.name = ?', $name)
        ->limit(1)
        ->fetchOne()
      ;
    }
}
