<?php

/**
 * Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cheapon
 * @subpackage model
 * @author     slowpokes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Event extends BaseEvent
{
  public function getCouponsCount()
  {
    $q = Doctrine_Query::create()
      ->select('COUNT(c.id) as number_of_coupons')
      ->from('Event e')
      ->leftJoin('e.Coupons c')
      ->where('e.id = ?', $this->id);
   
    return $q->fetchOne()->getNumberOfCoupons();
  }

  public function getCommentsCount()
  {
    $q = Doctrine_Query::create()
      ->select('COUNT(c.id) as number_of_comments')
      ->from('Event e')
      ->leftJoin('e.Comments c')
      ->where('e.id = ?', $this->id);
   
    return $q->fetchOne()->getNumberOfComments();
  }

  public function getReadCount($user_id)
  {
    $q = Doctrine_Query::create()
      ->select('COUNT(c.id) as number_of_comments')
      ->from('sfGuardUser u')
      ->leftJoin('u.ReadComments c')
      ->where('u.id = ?', $user_id)
      ->andWhere('c.event_id = ?', $this->id);
   
    return $q->fetchOne()->getNumberOfComments();
  }

  public function getETA()
  {
    return 'DUMMY ETA';
  }

  public function getLikesCount()
  {
    return 'DUMMY';
  }

  public function getActiveDates()
  {
    return [
      'from' => date('d.m', strtotime($this->getEventStart())),
      'to' => date('d.m', strtotime($this->getEventEnd())),
    ];
  }
}
