<?php

/**
 * RefEventLikeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefEventLikeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefEventLikeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RefEventLike');
    }
}