# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

feedback:
  url:   /page/contacts
  param: { module: feedback, action: new }

faq:
  url:   /page/faq
  param: { module: page, action: faq }

page:
  url:   /page/:slug
  param: { module: page, action: show }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
