# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

personal:
  url:   /personal
  param: { module: personal, action: index }

sf_guard_register:
  url:   /personal/register
  param: { module: sfGuardRegister, action: index }

sf_guard_signin:
  url:   /personal/login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /personal/logout
  param: { module: sfGuardAuth, action: signout }

homepage:
  url:   /:past/:category
  param: { module: event, action: index, category: all, past: false }

show-event:
  url:   /event/show/:id
  param: { module: event, action: show }
  requirements: { id: \d+ }

feedback:
  url:   /page/contacts
  param: { module: feedback, action: new }

faq:
  url:   /page/faq
  param: { module: page, action: faq }

page:
  url:   /page/:slug
  param: { module: page, action: show }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
