<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('provider', 'user_id', 'integer', '8', array(
             'notnull' => '',
             ));
        $this->changeColumn('provider_version', 'user_id', 'integer', '8', array(
             'notnull' => '',
             ));
    }

    public function down()
    {

    }
}