<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ref_comment_read', 'ref_comment_read_user_id_sf_guard_user_id', array(
             'name' => 'ref_comment_read_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('ref_comment_read', 'ref_comment_read_comment_id_comment_id', array(
             'name' => 'ref_comment_read_comment_id_comment_id',
             'local' => 'comment_id',
             'foreign' => 'id',
             'foreignTable' => 'comment',
             ));
        $this->addIndex('ref_comment_read', 'ref_comment_read_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('ref_comment_read', 'ref_comment_read_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ref_comment_read', 'ref_comment_read_user_id_sf_guard_user_id');
        $this->dropForeignKey('ref_comment_read', 'ref_comment_read_comment_id_comment_id');
        $this->removeIndex('ref_comment_read', 'ref_comment_read_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('ref_comment_read', 'ref_comment_read_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
    }
}