<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('faq', 'sort', 'integer', '8', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('faq_version', 'sort', 'integer', '8', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('faq', 'sort');
        $this->removeColumn('faq_version', 'sort');
    }
}