<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('page', 'page_created_by_sf_guard_user_id', array(
             'name' => 'page_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('page', 'page_updated_by_sf_guard_user_id', array(
             'name' => 'page_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('page_version', 'page_version_id_page_id', array(
             'name' => 'page_version_id_page_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'page',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('page', 'page_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('page', 'page_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
        $this->addIndex('page_version', 'page_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('page', 'page_created_by_sf_guard_user_id');
        $this->dropForeignKey('page', 'page_updated_by_sf_guard_user_id');
        $this->dropForeignKey('page_version', 'page_version_id_page_id');
        $this->removeIndex('page', 'page_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('page', 'page_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
        $this->removeIndex('page_version', 'page_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}