<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('event', 'photo1', 'string', '255', array(
             'notnull' => '',
             ));
        $this->changeColumn('event', 'photo2', 'string', '255', array(
             'notnull' => '',
             ));
        $this->changeColumn('event', 'photo3', 'string', '255', array(
             'notnull' => '',
             ));
        $this->changeColumn('event_version', 'photo1', 'string', '255', array(
             'notnull' => '',
             ));
        $this->changeColumn('event_version', 'photo2', 'string', '255', array(
             'notnull' => '',
             ));
        $this->changeColumn('event_version', 'photo3', 'string', '255', array(
             'notnull' => '',
             ));
    }

    public function down()
    {

    }
}