<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('category', 'sort', 'integer', '8', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('category_version', 'sort', 'integer', '8', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->changeColumn('event', 'category_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('event_version', 'category_id', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('category', 'sort');
        $this->removeColumn('category_version', 'sort');
    }
}