<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('city', 'is_default', 'boolean', '25', array(
             'default' => 'false',
             'notnull' => '1',
             ));
        $this->addColumn('city_version', 'is_default', 'boolean', '25', array(
             'default' => 'false',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('city', 'is_default');
        $this->removeColumn('city_version', 'is_default');
    }
}