<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('faq', 'answer', 'clob', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('faq_version', 'answer', 'clob', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}