<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('feedback', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'message' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('city', 'slug', 'string', '32', array(
             'default' => 'vladivostok',
             'notnull' => '1',
             ));
        $this->addColumn('city_version', 'slug', 'string', '32', array(
             'default' => 'vladivostok',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('feedback');
        $this->removeColumn('city', 'slug');
        $this->removeColumn('city_version', 'slug');
    }
}