<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('category', 'category_created_by_sf_guard_user_id', array(
             'name' => 'category_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('category', 'category_updated_by_sf_guard_user_id', array(
             'name' => 'category_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('event', 'event_category_id_category_id', array(
             'name' => 'event_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->createForeignKey('category_version', 'category_version_id_category_id', array(
             'name' => 'category_version_id_category_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('category', 'category_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('category', 'category_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
        $this->addIndex('event', 'event_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('category_version', 'category_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('category', 'category_created_by_sf_guard_user_id');
        $this->dropForeignKey('category', 'category_updated_by_sf_guard_user_id');
        $this->dropForeignKey('event', 'event_category_id_category_id');
        $this->dropForeignKey('category_version', 'category_version_id_category_id');
        $this->removeIndex('category', 'category_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('category', 'category_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
        $this->removeIndex('event', 'event_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('category_version', 'category_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}