<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('category', 'slug', 'string', '64', array(
             'default' => '',
             'notnull' => '1',
             ));
        $this->addColumn('category_version', 'slug', 'string', '64', array(
             'default' => '',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('category', 'slug');
        $this->removeColumn('category_version', 'slug');
    }
}