<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('image', 'image_provider_id_provider_id', array(
             'name' => 'image_provider_id_provider_id',
             'local' => 'provider_id',
             'foreign' => 'id',
             'foreignTable' => 'provider',
             ));
        $this->addIndex('image', 'image_provider_id', array(
             'fields' => 
             array(
              0 => 'provider_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('image', 'image_provider_id_provider_id');
        $this->removeIndex('image', 'image_provider_id', array(
             'fields' => 
             array(
              0 => 'provider_id',
             ),
             ));
    }
}