<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('comment', 'comment_answered_by_sf_guard_user_id', array(
             'name' => 'comment_answered_by_sf_guard_user_id',
             'local' => 'answered_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('comment', 'comment_answered_by', array(
             'fields' => 
             array(
              0 => 'answered_by',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('comment', 'comment_answered_by_sf_guard_user_id');
        $this->removeIndex('comment', 'comment_answered_by', array(
             'fields' => 
             array(
              0 => 'answered_by',
             ),
             ));
    }
}