<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('image', 'image_gallery_id_gallery_id');
    }

    public function down()
    {
        $this->createForeignKey('image', 'image_gallery_id_gallery_id', array(
             'name' => 'image_gallery_id_gallery_id',
             'local' => 'gallery_id',
             'foreign' => 'id',
             'foreignTable' => 'gallery',
             ));
    }
}