<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('provider', 'phone');
        $this->removeColumn('provider_version', 'phone');
    }

    public function down()
    {
        $this->addColumn('provider', 'phone', 'clob', '', array(
             'default' => '',
             'notnull' => '1',
             ));
        $this->addColumn('provider_version', 'phone', 'clob', '', array(
             'default' => '',
             'notnull' => '1',
             ));
    }
}