<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('sf_guard_user', 'city_id', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}