<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version27 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sf_guard_user', 'phone', 'string', '255', array(
             ));
        $this->addColumn('sf_guard_user', 'city_id', 'integer', '8', array(
             'default' => '1',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('sf_guard_user', 'phone');
        $this->removeColumn('sf_guard_user', 'city_id');
    }
}